use simplerecipes;

INSERT INTO tags (tag_name)
VALUES 	('Healthy'),
		    ('Cook With Friends'),
        ('Easy'),
		    ('Challenging'),
        ('Low Calorie'),
        ('Party'),
        ('Eat Everyday'),
        ('Rich'),
        ('Light'),
        ('Savory'),
        ('Sweet'),
        ('Spicy'),
        ('Creamy'),
        ('Crunchy'),
        ('Fresh'),
        ('Date Night'),
        ('Limited Cleaning');

INSERT INTO tools (tool_name)
VALUES 	('Skillet'),
		    ('Frying Pan'),
        ('Saucepot'),
        ('Soup Pot'),
        ('Wok'),
        ('Baking Sheet'),
        ('Baking Dish'),
        ('Tongs'),
        ('Spatula'),
        ('Whisk'),
        ('Spoon'),
        ('Strainer'),
        ('Chopsticks'),
        ('Fork'),
        ('Measuring Cup Set'),
        ('Measuring Spoon Set'),
        ('Chef\'s Knife'),
        ('Paring Knife'),
        ('Scissors'),
        ('Vegetable Peeler'),
        ('Grater'),
        ('Rolling Pin'),
        ('Masher'),
        ('Butter Knife');